name: CI

on: [push]

jobs:
  build:
    name: Build with tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        env:
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew test
